### ISSUE TITLE
Dashboard's script sales chart start dates are wrong

### ISSUE THREAD

**Issue by 0wain** [gmodstore/gmodstore-issues#152]
If you have a script submitted after the start of the year, it still thinks that the script was submitted in january. Example:
![](https://i.amowa.in/7xdsj9Rw.png)

**Comment by ExtReMLapin** [comment]
cut ur hairs!!!

**Comment by Marcuzz** [comment]
I'm not sure I understand this issue. What's the expected result, and what graph even is this?

**Comment by ExtReMLapin** [comment]
the script was released in (for example) april, but it shows sales in january

**Comment by OwjoTheGreat** [comment]
Sorry, I probably could have explained this better.

It's the "Purchases by addon" chart on the dashboard. Addons released later this year have their start dates set to January. Pretty much what Lapin said.

![](https://i.amowa.in/UF3fGrOX.png)

**Comment by ExtReMLapin** [comment]
wait do you mean the graph of some addons should start after january OR  : 

the addon was released the 3rd month of the year but all the sales are shown as date = date - 3 months

**Comment by OwjoTheGreat** [comment]
Let's use pVault as an example. I was released on the 6th month (June) of this year, yet the graph thinks it started on January. Meaning that all its sales over the last 2 months are applied to January and February rather than June and July. So when on the dashboard and looking at the "Purchases by Addon" chart, the graph starts high and then goes to 0 for the rest of the year (Till current date) (Look at my first screenshot for an example). This also happens with script specific charts when looking at individual scripts data. For example, if I go to pVaults info page, the chart once again starts in January rather than June.
Example:
![](https://i.amowa.in/kJAhoFKJ.png)
The red line is where the chart should start.
They're basically missing their buffer from the start of the year to the date they were released.

This issue is for both the Dashboard's "Purchases by Addon" chart and an individual scripts "Sales" chart.

**Comment by Marcuzz** [comment]
Ah, I get what you mean. I will look into it now
